fix infinity loop for unfolding markdown headers

diff --git a/.github/workflows/melpazoid-release.yml b/.github/workflows/melpazoid-release.yml
--- a/.github/workflows/melpazoid-release.yml
+++ b/.github/workflows/melpazoid-release.yml
@@ -92,7 +92,8 @@ jobs:
         run: |
           echo $GITHUB_REF
           make -C ~/melpazoid |& tee output.log
-          [ $? -ne 0 ] && { echo "Make command failed, failing workflow"; exit 1; }
+          make_exit=${PIPESTATUS[0]}
+          [ $make_exit -ne 0 ] && { echo "Make command failed, failing workflow"; exit 1; }
           if grep -q "Warning" output.log ; then
             echo "Warnings detected, failing workflow" ; exit 1
           fi
diff --git a/.github/workflows/melpazoid.yml b/.github/workflows/melpazoid.yml
--- a/.github/workflows/melpazoid.yml
+++ b/.github/workflows/melpazoid.yml
@@ -22,19 +22,21 @@ jobs:
           - release-snapshot
     steps:
       - name: Get repo to access in conteiner
-        uses: actions/checkout@v5
+        uses: actions/checkout@v6
         with:
           fetch-depth: 1
       - name: Set up Python 3.12
         uses: actions/setup-python@v5
         with:
           python-version: 3.12
+
       - name: Install melpazoid
         run: |
           python -m pip install --upgrade pip
           # sudo apt-get install emacs-nox && emacs --version
           git clone https://github.com/riscy/melpazoid.git ~/melpazoid
           pip install ~/melpazoid
+
       - name: Install Emacs
         uses: purcell/setup-emacs@master
         with:
@@ -88,7 +90,8 @@ jobs:
         run: |
           echo $GITHUB_REF
           make -C ~/melpazoid |& tee output.log
-          [ $? -ne 0 ] && { echo "Make command failed, failing workflow"; exit 1; }
+          make_exit=${PIPESTATUS[0]}
+          [ $make_exit -ne 0 ] && { echo "Make command failed, failing workflow"; exit 1; }
           if grep -q "Warning" output.log ; then
             echo "Warnings detected, failing workflow" ; exit 1
           fi
